// Mocks generated by Mockito 5.0.16 from annotations
// in contact_form/test/use_cases/store_contact_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:contact_form/network/http_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  String get applicationKey =>
      (super.noSuchMethod(Invocation.getter(#applicationKey), returnValue: '')
          as String);
  @override
  _i3.Future<dynamic> get(String? path) =>
      (super.noSuchMethod(Invocation.method(#get, [path]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(String? path, Map<String, dynamic>? data) =>
      (super.noSuchMethod(Invocation.method(#post, [path, data]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  Map<String, String> createHeaders() =>
      (super.noSuchMethod(Invocation.method(#createHeaders, []),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  String toString() => super.toString();
}
