name: widget test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  widget_test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.1'
      - run: flutter pub get
      - run: flutter test
